### ISSUE TITLE
Some missing steps in the instructions

### ISSUE THREAD

**Issue by andybak** [Barbelot/Physarum3D#1]
I'm gradually working through and getting to the stage where I have a working example but there is a simpler way - post a working project instead of a partial project + instructions.

As someone that downloads an unusually high number of Unity Github projects to try them out (it's how I learn best)  can I share a pattern I've observer? Repos that contain an entire Unity project nearly always work. Repos that don't do this have a much higher failure rate - especially as more time passes and more bitrot sets in!

I'll post my project once I've got it working if that helps.

**Comment by Barbelot** [comment]
Hello, thank you for your feedback.

This project is designed to be used as a submodule (or a plugin) in a Unity project and therefore is not a full Unity project. This is intended as it allows seamless integration in any project (through submodules or juste pasting these files directly). The drawback is indeed that it does not work out of the box.

If the instructions are unclear or some of them are missing, please tell me.

**Comment by andybak** [comment]
Hiya,

Yes - that was my point. Seamless integration is only useful if it's easy to get a working example up and running. And the simplest way to get a working example is to post an entire project with example scenes.

(Check out how Keijiro structures his projects - master branch is a Unity project with a UPM branch that can be added directly to packages.json)

There's other approaches that might be easier for the the repo maintainer (i.e. you!) - but I'd really  recommend making a full project available some how if you want to ensure people can make use of your hard work.

Great looking project by the way. Thanks!

**Comment by Barbelot** [comment]
An example scene is something I could add indeed, I'll look at it.
Thanks !

**Comment by Barbelot** [comment]
I will look at an example scene but it creates many dependencies depending on how you want to visualize the particles that I don't really like. This is supposed to only be the core scripts and shaders to compute the particles movement.
Different branches is an interesting option, I'll try to add a minimal project branch when I get some time to get this project running again.
Thanks !

**Comment by andybak** [comment]
Maybe add a link to this in the readme: https://github.com/miketucker/Physarum3D

I tried again and spent 20m trying to get your repo working (and failed) but the linked version which adds a working sample project worked first time.

I appreciate your position on this but I install __a lot__ or projects from Github for learning and exploration and in my experience, the ones packaged as projects work 99% of the time and the ones that don't work 50% of the time. (You can have your cake and eat it too - use https://github.com/adrenak/upm-template )

Now it's working - great project! Really inspiring.

**Comment by Barbelot** [comment]
Hi, thank you for the link, I'll add it to the README.

The UPM package workflow seems really interesting but I'll have to take a closer look at it to understand how it works and how I can set it up. Thank you for the information.

If I ever get some time to work on this project again I'll try to update it.
