### ISSUE TITLE
Is this using DirectX

### ISSUE THREAD

**Issue by nejurgis** [Barbelot/Physarum3D#2]
Running on a mac with Metal and can't seem to run it. Is physarum formed and visible by the VFX graph particles? Maybe you could show a screenshot of the VFX graph/Hierarchy configuration?

**Comment by Barbelot** [comment]
Hello,
I did not test on Mac so I can't say how it is running.
The physarum is computed in computebuffers and the VFX Graph is only used to render the particles from the physarum particle buffer.

**Comment by Barbelot** [comment]
I added an example VFXGraph to the repo : 

![image](https://user-images.githubusercontent.com/2972871/109479431-aa7f4b80-7a7a-11eb-8ebd-22d4b0b81639.png)
